# Generated by Django 3.1.1 on 2020-09-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiments',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
